name: Build and Compile ZSnoW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - name: Update and Install Base Dependencies
        run: |
          dnf update -y
          dnf install -y git curl make gcc libwayland-devel wayland-protocols-devel

      - name: Install Zig
        run: |
          curl -LO https://ziglang.org/download/index.json
          LATEST_ZIG=$(curl -s https://ziglang.org/download/index.json | grep 'master' | head -n 1 | sed -E 's/.*"(https[^"]+linux-x86_64.tar.xz)".*/\1/')
          curl -LO $LATEST_ZIG
          tar -xf zig-linux-x86_64.tar.xz
          mv zig-linux-x86_64/ /usr/local/zig
          ln -s /usr/local/zig/zig /usr/local/bin/zig

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build ZSnoW
        run: |
          cd $GITHUB_WORKSPACE
          zig build -Drelease-safe
          ls zig-out/bin

      - name: Copy Executable
        run: |
          mkdir -p /zsnow
          cp zig-out/bin/* /zsnow/
          echo "Executable copied to /zsnow"

      - name: Run ZSnoW
        run: |
          /zsnow/zsnow --version || echo "ZSnoW built successfully!"
